# GitHub Action – Black Duck Security Scan:
#     https://documentation.blackduck.com/bundle/bridge/page/documentation/c_using-github-action.html
# GitHub Prerequisites:
#     https://documentation.blackduck.com/bundle/bridge/page/documentation/c_github-prerequisites.html
# Additional GitHub Configuration:
#     https://documentation.blackduck.com/bundle/bridge/page/documentation/c_additional-github-parameters.html
# Using the Black Duck Security Scan Action with Black Duck SCA:
#     https://documentation.blackduck.com/bundle/bridge/page/documentation/c_github-blackduck.html
# Using Bridge CLI with Black Duck SCA:
#     https://documentation.blackduck.com/bundle/bridge/page/documentation/c_using-bridge-with-black-duck.html
name: Black Duck Security Scan
on:
  push:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  pull_request:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  workflow_dispatch: {}
jobs:
  blackducksca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Black Duck Security Scan
        id: black-duck-security-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
